# Site settings
title: supagraph
email: hello@supagraph.com
description: >-
  The Open Source Graph Database.
baseurl: ""
url: "https://supagraph.com"
github_username: supagraph-ai

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .gitignore
  - README.md
  - LICENSE

# Collections
collections:
  docs:
    output: true
    permalink: /docs/:path/

# Default settings
defaults:
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: "_docs"
    values:
      layout: "page"
